services:
  ollama:
    image: ollama/ollama:0.19.0
    container_name: ollama-server
    env_file:
      - ./config/.env
    volumes:
      - /data/.ollama:/root/.ollama
    ports:
      - '${OLLAMA_PORT:-11434}:11434'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-1h}
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
    networks:
      - llm-network
    restart: unless-stopped

networks:
  llm-network:
    external: true
